import { Component, ComponentType, DEFAULT_PROPS } from "@/types/intent";

function propsToJsx(props: Record<string, unknown>): string {
  const entries = Object.entries(props);
  if (entries.length === 0) return "";

  const propsStr = entries
    .filter(([key]) => key !== "children")
    .map(([key, value]) => {
      if (key === "className") return ` className="${value}"`;
      if (key === "text") return "";
      if (typeof value === "string") return ` ${key}="${value}"`;
      if (typeof value === "number") return ` ${key}={${value}}`;
      if (typeof value === "boolean") return value ? ` ${key}` : "";
      return ` ${key}={${JSON.stringify(value)}}`;
    })
    .join("");

  return propsStr;
}

function componentToJsx(component: Component, indent: number = 2): string {
  const spaces = " ".repeat(indent);
  const { type, props, children } = component;
  const propsStr = propsToJsx(props || {});

  const textContent = props?.text as string | undefined;
  const hasChildren = children && children.length > 0;
  const hasText = textContent && !hasChildren;

  switch (type) {
    case "input":
    case "checkbox":
    case "radio":
      return `${spaces}<${type}${propsStr} />`;

    case "image":
      return `${spaces}<img${propsStr} />`;

    case "heading": {
      const level = props?.level || 1;
      const Tag = `h${level}`;
      if (hasChildren) {
        const childrenJsx = children.map((c) => componentToJsx(c, indent + 2)).join("\n");
        return `${spaces}<${Tag}${propsStr}>\n${childrenJsx}\n${spaces}</${Tag}>`;
      }
      return `${spaces}<${Tag}${propsStr}>${hasText ? textContent : ""}</${Tag}>`;
    }

    default: {
      const Tag = type === "text" ? "span" : type === "paragraph" ? "p" : type;
      if (hasChildren) {
        const childrenJsx = children.map((c) => componentToJsx(c, indent + 2)).join("\n");
        return `${spaces}<${Tag}${propsStr}>\n${childrenJsx}\n${spaces}</${Tag}>`;
      }
      if (hasText) {
        return `${spaces}<${Tag}${propsStr}>${textContent}</${Tag}>`;
      }
      return `${spaces}<${Tag}${propsStr} />`;
    }
  }
}

export function generatePageCode(components: Component[]): string {
  const componentsJsx = components.map((c) => componentToJsx(c, 4)).join("\n");

  return `export default function Page() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center p-8">
${componentsJsx || '      <p className="text-lg">No components yet</p>'}
    </div>
  );
}
`;
}

export function generateLayoutCode(): string {
  return `import type { Metadata } from "next";
import { LingoProvider } from "@lingo.dev/compiler/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Exported App",
  description: "Generated by Voice-Native Runtime",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <LingoProvider>
      <html lang="en">
        <body className="antialiased">{children}</body>
      </html>
    </LingoProvider>
  );
}
`;
}

export function generateGlobalsCss(): string {
  return `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: system-ui, sans-serif;
}
`;
}

export function generatePackageJson(): string {
  return JSON.stringify(
    {
      name: "exported-app",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "^15.0.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        "@lingo.dev/compiler": "^0.1.0",
      },
      devDependencies: {
        "@types/node": "^20.0.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        typescript: "^5.0.0",
        tailwindcss: "^4.0.0",
        postcss: "^8.0.0",
      },
    },
    null,
    2
  );
}

export function generateNextConfig(): string {
  return `import type { NextConfig } from "next";
import { withLingo } from "@lingo.dev/compiler/next";

const nextConfig: NextConfig = {};

export default async function () {
  return await withLingo(nextConfig, {
    sourceLocale: "en",
    targetLocales: ["kn", "hi"],
    models: "lingo.dev",
  });
}
`;
}

export function generateLingoConfig(): string {
  return `import { defineConfig } from "@lingo.dev/compiler";

export default defineConfig({
  defaultLocale: "en",
  locales: ["en", "kn", "hi"],
});
`;
}

export function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

export function generatePostcssConfig(): string {
  return `export default {
  plugins: {
    tailwindcss: {},
  },
};
`;
}

export interface ExportedProject {
  files: { path: string; content: string }[];
}

export function exportProject(components: Component[]): ExportedProject {
  return {
    files: [
      { path: "app/page.tsx", content: generatePageCode(components) },
      { path: "app/layout.tsx", content: generateLayoutCode() },
      { path: "app/globals.css", content: generateGlobalsCss() },
      { path: "package.json", content: generatePackageJson() },
      { path: "next.config.ts", content: generateNextConfig() },
      { path: "lingo.config.ts", content: generateLingoConfig() },
      { path: "tsconfig.json", content: generateTsConfig() },
      { path: "postcss.config.mjs", content: generatePostcssConfig() },
    ],
  };
}
