import {
  ProjectFileSystem,
  FileSystemNode,
  FileNode,
  DirectoryNode,
  createFile,
  createDirectory,
  isFile,
  isDirectory,
} from "@/types/filesystem";

function createDefaultProject(): ProjectFileSystem {
  const appDir = createDirectory("app");
  const configDir = createDirectory("config");
  
  const pageFile = createFile("app/page.tsx", `export default function Page() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
      <p>No components yet</p>
    </main>
  );
}
`);

  const layoutFile = createFile("app/layout.tsx", `import type { Metadata } from "next";
import { LingoProvider } from "@lingo.dev/compiler/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Voice-Native Project",
  description: "Generated by Voice-Native Runtime",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LingoProvider>
      <html lang="en">
        <body className="antialiased">{children}</body>
      </html>
    </LingoProvider>
  );
}
`);

  const globalsFile = createFile("app/globals.css", `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: system-ui, -apple-system, sans-serif;
}
`);

  const nextConfig = createFile("config/next.config.ts", `import type { NextConfig } from "next";
import { withLingo } from "@lingo.dev/compiler/next";

const nextConfig: NextConfig = {};

export default async function (): Promise<NextConfig> {
  return await withLingo(nextConfig, {
    sourceLocale: "en",
    targetLocales: ["kn", "hi"],
    models: "lingo.dev",
  });
}
`);

  const lingoConfig = createFile("config/lingo.config.ts", `import { defineConfig } from "@lingo.dev/compiler";

export default defineConfig({
  defaultLocale: "en",
  locales: ["en", "kn", "hi"],
});
`);

  const i18nJson = createFile("config/i18n.json", JSON.stringify({
    version: 1,
    defaultLocale: "en",
    locales: ["en", "kn", "hi"],
    bucket: { adapter: "vercel-blob" },
    source: {
      adapter: "next-js",
      include: ["app/**/*.{tsx,ts,jsx,js}"],
      exclude: ["app/api/**", "node_modules/**"],
    },
    storage: { adapter: "vercel-blob" },
    rules: [{ patterns: ["**/*.tsx"], extract: "jsx-text" }],
  }, null, 2) + "\n");

  const packageJson = createFile("config/package.json", JSON.stringify({
    name: "voice-native-project",
    version: "1.0.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
      "lingo:run": "lingo.dev run",
      "lingo:frozen": "lingo.dev run --frozen",
      localize: "npm run lingo:run && npm run build",
    },
    dependencies: {
      next: "15.1.6",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "@lingo.dev/compiler": "^0.3.8",
    },
    devDependencies: {
      "@types/node": "^20",
      "@types/react": "^19",
      "@types/react-dom": "^19",
      typescript: "^5",
      tailwindcss: "^4",
      postcss: "^8",
      eslint: "^9",
      "eslint-config-next": "15.1.6",
      "lingo.dev": "^0.131.0",
    },
  }, null, 2) + "\n");

  const componentsDir = createDirectory("app/components");

  appDir.children = [pageFile, layoutFile, globalsFile, componentsDir];
  configDir.children = [nextConfig, lingoConfig, i18nJson, packageJson];

  const root = createDirectory("");
  root.name = "project";
  root.path = "";
  root.children = [appDir, configDir];

  return {
    root,
    version: 1,
    projectName: "voice-native-project",
  };
}

function findNodeByPath(
  node: FileSystemNode,
  path: string
): FileSystemNode | null {
  if (node.path === path) return node;

  if (isDirectory(node)) {
    for (const child of node.children) {
      const found = findNodeByPath(child, path);
      if (found) return found;
    }
  }

  return null;
}

function findParentDirectory(
  node: FileSystemNode,
  path: string
): DirectoryNode | null {
  const segments = path.split("/").filter(Boolean);
  if (segments.length === 0) return null;

  segments.pop();
  const parentPath = segments.join("/");

  if (parentPath === "") return isDirectory(node) ? node : null;

  const parent = findNodeByPath(node, parentPath);
  return parent && isDirectory(parent) ? parent : null;
}

function insertFile(
  root: DirectoryNode,
  filePath: string,
  content: string
): boolean {
  const parent = findParentDirectory(root, filePath);
  if (!parent) return false;

  const existingIndex = parent.children.findIndex((c) => c.path === filePath);
  const newFile = createFile(filePath, content);

  if (existingIndex >= 0) {
    parent.children[existingIndex] = newFile;
  } else {
    parent.children.push(newFile);
  }

  parent.lastModified = Date.now();
  return true;
}

function insertDirectory(root: DirectoryNode, dirPath: string): boolean {
  const segments = dirPath.split("/").filter(Boolean);
  if (segments.length === 0) return false;

  let current = root;

  for (let i = 0; i < segments.length; i++) {
    const segment = segments[i];
    const currentPath = segments.slice(0, i + 1).join("/");

    const child = current.children.find((c) => c.name === segment && isDirectory(c));

    if (!child) {
      const newDir = createDirectory(currentPath);
      current.children.push(newDir);
      current = newDir;
    } else if (isDirectory(child)) {
      current = child;
    } else {
      return false;
    }
  }

  return true;
}

function deleteNode(root: DirectoryNode, path: string): boolean {
  if (path === "") return false;

  const parent = findParentDirectory(root, path);
  if (!parent) return false;

  const index = parent.children.findIndex((c) => c.path === path);
  if (index < 0) return false;

  parent.children.splice(index, 1);
  parent.lastModified = Date.now();
  return true;
}

function updateFileContent(
  root: DirectoryNode,
  filePath: string,
  content: string
): boolean {
  const node = findNodeByPath(root, filePath);
  if (!node || !isFile(node)) return false;

  node.content = content;
  node.lastModified = Date.now();
  return true;
}

function renameNode(
  root: DirectoryNode,
  oldPath: string,
  newName: string
): boolean {
  const node = findNodeByPath(root, oldPath);
  if (!node) return false;

  const parent = findParentDirectory(root, oldPath);
  if (!parent) return false;

  const segments = oldPath.split("/").filter(Boolean);
  segments[segments.length - 1] = newName;
  const newPath = segments.join("/");

  node.name = newName;
  node.path = newPath;

  if (isFile(node)) {
    node.fileType = getFileTypeFromName(newName);
  }

  parent.lastModified = Date.now();
  return true;
}

function getFileTypeFromName(name: string): FileNode["fileType"] {
  const ext = name.split(".").pop()?.toLowerCase();
  switch (ext) {
    case "tsx": return "tsx";
    case "ts": return "ts";
    case "jsx": return "jsx";
    case "js": return "js";
    case "css": return "css";
    case "json": return "json";
    case "md": return "md";
    case "mjs": return "mjs";
    default: return "unknown";
  }
}

function collectAllFiles(node: FileSystemNode): FileNode[] {
  const files: FileNode[] = [];

  if (isFile(node)) {
    files.push(node);
  } else if (isDirectory(node)) {
    for (const child of node.children) {
      files.push(...collectAllFiles(child));
    }
  }

  return files;
}

function collectAllDirectories(node: FileSystemNode): DirectoryNode[] {
  const dirs: DirectoryNode[] = [];

  if (isDirectory(node)) {
    dirs.push(node);
    for (const child of node.children) {
      dirs.push(...collectAllDirectories(child));
    }
  }

  return dirs;
}

function cloneFileSystem(node: FileSystemNode): FileSystemNode {
  if (isFile(node)) {
    return { ...node };
  }

  return {
    ...node,
    children: node.children.map(cloneFileSystem) as (FileNode | DirectoryNode)[],
  };
}

function getFileContent(root: DirectoryNode, path: string): string | null {
  const node = findNodeByPath(root, path);
  return node && isFile(node) ? node.content : null;
}

export {
  createDefaultProject,
  findNodeByPath,
  findParentDirectory,
  insertFile,
  insertDirectory,
  deleteNode,
  updateFileContent,
  renameNode,
  collectAllFiles,
  collectAllDirectories,
  cloneFileSystem,
  getFileContent,
};
