import { Component } from "@/types/intent";
import { componentToJsx } from "./projectExporter";

export function generatePageContent(components: Component[]): string {
  const sortedComponents = [...components].sort((a, b) => a.id.localeCompare(b.id));
  const componentsJsx = sortedComponents
    .map((c) => componentToJsx(c, 4))
    .join("\n");

  return `export default function Page() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
${componentsJsx || '      <p>No components yet</p>'}
    </main>
  );
}
`;
}

export function generateComponentFile(
  componentName: string,
  components: Component[],
  isDefaultExport: boolean = true
): string {
  const sortedComponents = [...components].sort((a, b) => a.id.localeCompare(b.id));
  const componentsJsx = sortedComponents
    .map((c) => componentToJsx(c, 4))
    .join("\n");

  const exportKeyword = isDefaultExport ? "default " : "";
  const componentContent = componentsJsx || '    <div>No content</div>';

  return `export ${exportKeyword}function ${componentName}() {
  return (
${componentContent}
  );
}
`;
}

export function updatePageFile(
  existingContent: string,
  components: Component[]
): string {
  const importMatch = existingContent.match(/^[\s\S]*?(?=export\s+(default\s+)?function)/);
  const imports = importMatch ? importMatch[0] : "";
  
  const newPageContent = generatePageContent(components);
  
  const hasImports = imports.trim().length > 0 && imports.includes("import");
  if (hasImports) {
    return imports + "\n" + newPageContent;
  }
  
  return newPageContent;
}

export function createNewComponentFileContent(
  componentName: string,
  componentType: string,
  props: Record<string, unknown>
): string {
  const defaultProps: Record<string, unknown> = {
    className: `px-4 py-2 rounded`,
    ...props,
  };

  const propsString = Object.entries(defaultProps)
    .filter(([key]) => key !== "children" && key !== "text")
    .map(([key, value]) => {
      if (typeof value === "string") return `${key}="${value}"`;
      if (typeof value === "number") return `${key}={${value}}`;
      if (typeof value === "boolean") return value ? key : "";
      return "";
    })
    .filter(Boolean)
    .join(" ");

  const tag = componentType === "heading" ? "h1" : componentType;
  const text = (props.text as string) || componentName;

  return `export default function ${componentName}() {
  return (
    <${tag}${propsString ? " " + propsString : ""}>
      ${text}
    </${tag}>
  );
}
`;
}

export function generateApiRouteFile(
  routeName: string,
  method: "GET" | "POST" | "PUT" | "DELETE" = "GET"
): string {
  return `import { NextResponse } from "next/server";

export async function ${method === "GET" ? "GET" : "POST"}() {
  return NextResponse.json({
    message: "${routeName} API endpoint",
    timestamp: new Date().toISOString(),
  });
}
`;
}

export function generateLayoutFile(
  title: string = "Voice-Native Project",
  description: string = "Generated by Voice-Native Runtime"
): string {
  return `import type { Metadata } from "next";
import { LingoProvider } from "@lingo.dev/compiler/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "${title}",
  description: "${description}",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LingoProvider>
      <html lang="en">
        <body className="antialiased">{children}</body>
      </html>
    </LingoProvider>
  );
}
`;
}

export function generateGlobalsCss(): string {
  return `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: system-ui, -apple-system, sans-serif;
}
`;
}

export function generateNextConfig(): string {
  return `import type { NextConfig } from "next";
import { withLingo } from "@lingo.dev/compiler/next";

const nextConfig: NextConfig = {};

export default async function (): Promise<NextConfig> {
  return await withLingo(nextConfig, {
    sourceLocale: "en",
    targetLocales: ["kn", "hi"],
    models: "lingo.dev",
  });
}
`;
}

export function generateLingoConfig(): string {
  return `import { defineConfig } from "@lingo.dev/compiler";

export default defineConfig({
  defaultLocale: "en",
  locales: ["en", "kn", "hi"],
});
`;
}

export function generateI18nJson(): string {
  return JSON.stringify({
    version: 1,
    defaultLocale: "en",
    locales: ["en", "kn", "hi"],
    bucket: { adapter: "vercel-blob" },
    source: {
      adapter: "next-js",
      include: ["app/**/*.{tsx,ts,jsx,js}"],
      exclude: ["app/api/**", "node_modules/**"],
    },
    storage: { adapter: "vercel-blob" },
    rules: [{ patterns: ["**/*.tsx"], extract: "jsx-text" }],
  }, null, 2) + "\n";
}

export function generatePackageJson(projectName: string = "voice-native-project"): string {
  return JSON.stringify({
    name: projectName,
    version: "1.0.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
      "lingo:run": "lingo.dev run",
      "lingo:frozen": "lingo.dev run --frozen",
      localize: "npm run lingo:run && npm run build",
    },
    dependencies: {
      next: "15.1.6",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "@lingo.dev/compiler": "^0.3.8",
    },
    devDependencies: {
      "@types/node": "^20",
      "@types/react": "^19",
      "@types/react-dom": "^19",
      typescript: "^5",
      tailwindcss: "^4",
      postcss: "^8",
      eslint: "^9",
      "eslint-config-next": "15.1.6",
      "lingo.dev": "^0.131.0",
    },
  }, null, 2) + "\n";
}
