import path from "path";
import fs from "fs/promises";
import { existsSync } from "fs";

async function writeText(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, "utf-8");
}

async function readText(filePath: string): Promise<string> {
  return await fs.readFile(filePath, "utf-8");
}

function extractBodyHtml(fullHtml: string): string {
  const bodyMatch = fullHtml.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  if (bodyMatch?.[1]) return bodyMatch[1].trim();
  return fullHtml.trim();
}

/**
 * If an imported zip is just a static landing page (e.g. code.html), scaffold
 * a minimal Next.js App Router project around it so Voxera can preview it.
 */
export async function ensureNextAppFromStaticZip(workspacePath: string): Promise<void> {
  const pkgPath = path.join(workspacePath, "package.json");
  if (existsSync(pkgPath)) return;

  const codeHtmlPath = path.join(workspacePath, "code.html");
  if (!existsSync(codeHtmlPath)) return;

  const html = await readText(codeHtmlPath);
  const bodyHtml = extractBodyHtml(html);

  await writeText(
    pkgPath,
    JSON.stringify(
      {
        name: "voxera-imported-landing",
        private: true,
        version: "0.0.0",
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
        },
        dependencies: {
          next: "16.1.6",
          react: "19.2.3",
          "react-dom": "19.2.3",
          "@lingo.dev/compiler": "^0.3.8",
          "react-rnd": "^10.5.2",
        },
        devDependencies: {
          typescript: "^5",
          "@types/node": "^20",
          "@types/react": "^19",
          "@types/react-dom": "^19",
        },
      },
      null,
      2,
    ) + "\n",
  );

  await writeText(
    path.join(workspacePath, "next-env.d.ts"),
    "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// NOTE: This file is automatically generated by Next.js\n",
  );

  await writeText(
    path.join(workspacePath, "tsconfig.json"),
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2017",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: false,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [{ name: "next" }],
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"],
      },
      null,
      2,
    ) + "\n",
  );

  await writeText(
    path.join(workspacePath, "app", "globals.css"),
    "html, body { height: 100%; }\nbody { margin: 0; }\n",
  );

  await writeText(
    path.join(workspacePath, "app", "layout.tsx"),
    `import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: "Landing",\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n`,
  );

  await writeText(
    path.join(workspacePath, "app", "page.tsx"),
    `export default function Page() {\n  return (\n    <main style={{ minHeight: \"100vh\" }}>\n      <div suppressHydrationWarning dangerouslySetInnerHTML={{ __html: ${JSON.stringify(bodyHtml)} }} />\n    </main>\n  );\n}\n`,
  );
}
